// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var RnPaper = require("../adapters/RnPaper.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Header");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return ReasonReact.element(/* None */0, /* None */0, RnPaper.Toolbar[/* make */0](/* None */0, /* None */0, /* None */0, /* None */0, /* array */[
                      ReasonReact.element(/* None */0, /* None */0, RnPaper.ToolbarBackAction[/* make */0](/* None */0, /* Some */[(function () {
                                    return Curry._1(self[/* send */4], /* Back */0);
                                  })], /* None */0, /* array */[])),
                      ReasonReact.element(/* None */0, /* None */0, RnPaper.ToolbarContent[/* make */0]("Reason Events", /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* array */[]))
                    ]));
    });
  newrecord[/* reducer */12] = (function (_, _$1) {
      return /* SideEffects */Block.__(2, [(function () {
                    console.log("Back, please!");
                    return /* () */0;
                  })]);
    });
  return newrecord;
}

function fromJs(props) {
  return make(props.children);
}

var $$default = ReasonReact.wrapReasonForJs(component, fromJs);

exports.component = component;
exports.make = make;
exports.fromJs = fromJs;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* component Not a pure module */
