// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var Option$BsAbstract = require("bs-abstract/src/implementations/Option.bs.js");

function decodeDate(date) {
  return Curry._2(Option$BsAbstract.Infix[/* <#> */4], Js_json.decodeString(date), (function (prim) {
                return new Date(prim);
              }));
}

function encodeDate(date) {
  return date.toString();
}

exports.decodeDate = decodeDate;
exports.encodeDate = encodeDate;
/* Option-BsAbstract Not a pure module */
